### ISSUE TITLE
Centos build the rpm package, not support autocomlete and uparrow command. 

### ISSUE THREAD

**Issue by wangzhen11aaa** [Altinity/clickhouse-rpm#194]
How to reproduce
System CentOS 7
https://github.com/Altinity/clickhouse-rpm.git
clickhouse-rpm builder.
./builder build --rpms --from-sources-in-SOURCES-dir
then we will have
clickhouse-client-19.8.3.8-1.el7.x86_64.rpm clickhouse-debuginfo-19.8.3.8-1.el7.x86_64.rpm clickhouse-server-common-19.8.3.8-1.el7.x86_64.rpm
clickhouse-common-static-19.8.3.8-1.el7.x86_64.rpm clickhouse-server-19.8.3.8-1.el7.x86_64.rpm clickhouse-test-19.8.3.8-1.el7.x86_64.rpm
then
Reinstall clickhouse
sudo yum -y remove clickhouse-common-static.x86_64
sudo yum -y remove clickhouse-server-common.x86_64

cd /data/software/clickhouse-rpm/rpmbuild/RPMS/x86_64

sudo rpm -ivh clickhouse-common-static-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-server-common-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-server-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-client-19.8.3.8-1.el7.x86_64.rpm

sudo service clickhouse-server restart

then
connect to this server.
clickhouse-client
press uparrow
client shows ^[[A^[[A

Which ClickHouse server version to use
19.8.3.8 stable or above.
I have tried to use libtinfo.so and on the icu library, all failed. so help, appreciate in advance.

Expected behavior
When I press the uparrow it should show the previous command i input, empty if no command input previously input and Tab clickhosue client should autocomplete.
Error message and/or stacktrace
No error message in server's log.

**Comment by filimonov** [comment]
Did you install all the dependencies first?
./builder install --deps

If it will not help - please provide full cmake output

**Comment by wangzhen11aaa** [comment]
> Did you install all the dependencies first?
> ./builder install --deps
> 
> If it will not help - please provide full cmake output

ok, Now I found the library maybe not good. Let me try first and exclude the enviroment reasons.

**Comment by wangzhen11aaa** [comment]
> Did you install all the dependencies first?
> ./builder install --deps
> 
> If it will not help - please provide full cmake output

I find a problem. When I use the ./builder  install --build-deps, yum will update a lot of packages and the result is that the library version for build will be different with the machine online. How to resolve this problem.

**Comment by wangzhen11aaa** [comment]
What does this mean?
 7731 Requires(rpmlib): rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
  7732 Checking for unpackaged file(s): /usr/lib/rpm/check-files /data/software/clickhouse-rpm/rpmbuild/BUILDROOT/clickhouse-19.8.3.8-1.el7.x86_64
  7733
  7734
  7735 RPM build errors:
  7736 #########################################
  7737 ## RPMs build FAILED. Can not continue ##
  7738 #########################################

-------------------------------------------
When build rpms

**Comment by wangzhen11aaa** [comment]
Use cmake and make command, the program is ok. 
When use clichouse-rpm to build the project, It does not support autocomplete and the uparrow does not function well.

**Comment by wangzhen11aaa** [comment]
I  solved this problem. This problem is caused by the options of cmake.
When use RELITHDEBINFO,  clickhouse-client does not support autocomplete and uparrow. You should use RELEASE or MINSIZEREL.

**Comment by filimonov** [comment]
It should not be an issue. We always build clickhouse as RelWithDebugInfo and strip symbols afterwards, so do Yandex. You can just pick our rpm and check that autocomplite works there. 

https://github.com/Altinity/clickhouse-rpm-install
