### ISSUE TITLE
An error when building 

### ISSUE THREAD

**Issue by onine007** [Altinity/clickhouse-rpm#204]
centos7 

[ 56%] Linking CXX static library libicui18n.a
[ 56%] Built target icui18n
make: *** [all] Error 2
error: Bad exit status from /root/clickhouse-rpm/rpmbuild/TMP/rpm-tmp.YAsBPN (%build)

**Comment by onine007** [comment]
-- Detecting CXX compile features - done
-- Using custom linker by name: gold
-- IPO/LTO not enabled.
CMake Error at CMakeLists.txt:49 (message):
  Submodules are not initialized.  Run

        git submodule update --init --recursive


-- Configuring incomplete, errors occurred!
See also "/data/ck_rpm/clickhouse-rpm/rpmbuild/BUILD/ClickHouse-20.1.8.41-stable/build/CMakeFiles/CMakeOutput.log".
error: Bad exit status from /data/ck_rpm/clickhouse-rpm/rpmbuild/TMP/rpm-tmp.XwcrtA (%build)


RPM build errors:
    Bad exit status from /data/ck_rpm/clickhouse-rpm/rpmbuild/TMP/rpm-tmp.XwcrtA (%build)
+ banner 'RPMs build FAILED. Can not continue'
+ set +x
#########################################
## RPMs build FAILED. Can not continue ##
#########################################
+ exit 1

**Comment by sunsingerus** [comment]
looks like unstable connection to github and git is unable to fully download sources
