### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by i4late** [Altinity/clickhouse-rpm#224]
build evn:
centos 7.5 base on docker 

when i build clickhouse 20.*, the build error is 

FAILED: dbms/programs/clickhouse
: && /usr/local/bin/g++-9  -fdiagnostics-color=always -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -Wno-array-bounds -Wextra -Werror -Wshadow -O2 -g -DNDEBUG -O3  -Wl,--no-undefined   -rdynamic dbms/programs/CMakeFiles/clickhouse.dir/main.cpp.o  -o dbms/programs/clickhouse  dbms/libclickhouse_common_io.a  dbms/src/Common/StringUtils/libstring_utils.a  dbms/programs/server/libclickhouse-server-lib.a  dbms/programs/client/libclickhouse-client-lib.a  dbms/programs/local/libclickhouse-local-lib.a  dbms/programs/benchmark/libclickhouse-benchmark-lib.a  dbms/programs/performance-test/libclickhouse-performance-test-lib.a  dbms/programs/copier/libclickhouse-copier-lib.a  dbms/programs/extract-from-config/libclickhouse-extract-from-config-lib.a  dbms/programs/compressor/libclickhouse-compressor-lib.a  dbms/programs/format/libclickhouse-format-lib.a  dbms/programs/obfuscator/libclickhouse-obfuscator-lib.a  dbms/programs/server/libclickhouse-server-lib.a  dbms/programs/client/libclickhouse-client-lib.a  /usr/lib64/libreadline.so  -ltermcap  dbms/programs/client/readpassphrase/libreadpassphrase.a  libs/libdaemon/libdaemon.a  libs/libloggers/loggers/libloggers.a  dbms/src/Functions/libclickhouse_functions.a  dbms/src/Dictionaries/libclickhouse_dictionaries.a  libs/consistent-hashing/libconsistent-hashing.a  libs/consistent-hashing-sumbur/libconsistent-hashing-sumbur.a  contrib/libfarmhash/libfarmhash.a  contrib/libmetrohash/libmetrohash.a  contrib/murmurhash/libmurmurhash.a  contrib/base64-cmake/libbase64.a  contrib/fastops-cmake/libfastops.a  contrib/h3-cmake/libh3.a  dbms/src/Functions/URL/libclickhouse_functions_url.a  contrib/hyperscan/lib/libhs.a  dbms/src/Functions/array/libclickhouse_functions_array.a  dbms/src/Functions/GatherUtils/libclickhouse_functions_gatherutils.a  dbms/src/AggregateFunctions/libclickhouse_aggregate_functions.a  dbms/src/TableFunctions/libclickhouse_table_functions.a  dbms/src/Storages/System/libclickhouse_storages_system.a  dbms/libdbms.a  dbms/src/Common/Config/libclickhouse_common_config.a  dbms/src/Common/ZooKeeper/libclickhouse_common_zookeeper.a  dbms/src/Parsers/libclickhouse_parsers.a  contrib/boost-cmake/libboost_filesystem_internal.a  contrib/libbtrie/libbtrie.a  contrib/poco/Data/ODBC/libPocoDataODBC.a  contrib/unixodbc-cmake/libunixodbc.a  contrib/unixodbc-cmake/libltdl.a  contrib/poco/MongoDB/libPocoMongoDB.a  dbms/src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a  dbms/libclickhouse_common_io.a  dbms/src/Common/StringUtils/libstring_utils.a  libs/libwidechar_width/libwidechar_width.a  contrib/re2/libre2.a  contrib/re2_st/libre2_st.a  contrib/boost-cmake/libboost_program_options_internal.a  libs/libcommon/libapple_rt.a  contrib/croaring/libroaring.a  contrib/libcpuid/libcpuid.a  contrib/poco/Data/libPocoData.a  contrib/poco/NetSSL_OpenSSL/libPocoNetSSL.a  contrib/poco/Net/libPocoNet.a  contrib/poco/Crypto/libPocoCrypto.a  contrib/libhdfs3-cmake/libhdfs3.a  contrib/libxml2-cmake/liblibxml2.a  contrib/brotli-cmake/libbrotli.a  /usr/lib64/libicui18n.so  /usr/lib64/libicuuc.so  /usr/lib64/libicudata.so  contrib/cppkafka-cmake/libcppkafka.a  contrib/librdkafka-cmake/librdkafka.a  contrib/libgsasl/liblibgsasl.a  libs/libmysqlxx/libmysqlxx.a  libs/libcommon/libcommon.a  contrib/cityhash102/libcityhash.a  contrib/cctz-cmake/libcctz.a  -lstdc++fs  contrib/jemalloc-cmake/libjemalloc.a  libs/libmemcpy/libmemcpy.a  contrib/poco/Util/libPocoUtil.a  contrib/poco/XML/libPocoXML.a  contrib/poco/JSON/libPocoJSON.a  contrib/poco/Foundation/libPocoFoundation.a  -lpthread  -ldl  -lrt  contrib/boost-cmake/libboost_system_internal.a  contrib/mariadb-connector-c-cmake/libmysqlclient.a  contrib/ssl/ssl/libssl.a  contrib/ssl/crypto/libcrypto.a  contrib/capnproto-cmake/libcapnpc.a  contrib/capnproto-cmake/libcapnp.a  contrib/capnproto-cmake/libkj.a  contrib/arrow-cmake/libparquet_static.a  contrib/arrow-cmake/libarrow_static.a  contrib/double-conversion-cmake/libdouble-conversion.a  contrib/zlib-ng/libz.a  contrib/protobuf/cmake/libprotobuf.a  -pthread  contrib/lz4-cmake/liblz4.a  contrib/zstd-cmake/libzstd.a  contrib/snappy/libsnappy.a  contrib/arrow-cmake/libthrift_static.a  contrib/boost-cmake/libboost_regex_internal.a  -Wl,--start-group  libs/libglibc-compatibility/libglibc-compatibility.a  -l:libstdc++.a  -l:libstdc++fs.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_compress.c.o): in function `ZSTD_compressSequences_internal':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2041: undefined reference to `ZSTD_compressLiterals'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2083: undefined reference to `HIST_countFast_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2086: undefined reference to `ZSTD_selectEncodingType'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2093: undefined reference to `ZSTD_buildCTable'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2109: undefined reference to `HIST_countFast_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2115: undefined reference to `ZSTD_selectEncodingType'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2121: undefined reference to `ZSTD_buildCTable'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2137: undefined reference to `HIST_countFast_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2141: undefined reference to `ZSTD_selectEncodingType'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2147: undefined reference to `ZSTD_buildCTable'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2164: undefined reference to `ZSTD_encodeSequences'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_compress.c.o): in function `ZSTD_compressBlock_targetCBlockSize_body':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2567: undefined reference to `ZSTD_compressSuperBlock'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2567: undefined reference to `ZSTD_compressSuperBlock'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_compress.c:2567: undefined reference to `ZSTD_compressSuperBlock'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_sizeof_DCtx':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:82: undefined reference to `ZSTD_sizeof_DDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_findFrameSizeInfo':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:501: undefined reference to `ZSTD_getcBlockSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressContinue':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:898: undefined reference to `ZSTD_checkContinuity'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:929: undefined reference to `ZSTD_getcBlockSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:963: undefined reference to `ZSTD_decompressBlock_internal'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_insertBlock':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:575: undefined reference to `ZSTD_checkContinuity'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressContinue':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:898: undefined reference to `ZSTD_checkContinuity'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:929: undefined reference to `ZSTD_getcBlockSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:963: undefined reference to `ZSTD_decompressBlock_internal'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_loadDEntropy':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1099: undefined reference to `ZSTD_buildFSETable'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1114: undefined reference to `ZSTD_buildFSETable'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1129: undefined reference to `ZSTD_buildFSETable'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressMultiFrame':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:712: undefined reference to `ZSTD_DDict_dictContent'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:713: undefined reference to `ZSTD_DDict_dictSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressBegin_usingDDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1213: undefined reference to `ZSTD_DDict_dictContent'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1214: undefined reference to `ZSTD_DDict_dictSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1222: undefined reference to `ZSTD_copyDDictParameters'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressMultiFrame':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:761: undefined reference to `ZSTD_checkContinuity'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressFrame':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:643: undefined reference to `ZSTD_getcBlockSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:653: undefined reference to `ZSTD_decompressBlock_internal'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressBegin_usingDDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1213: undefined reference to `ZSTD_DDict_dictContent'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1214: undefined reference to `ZSTD_DDict_dictSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1222: undefined reference to `ZSTD_copyDDictParameters'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_DCtx_loadDictionary_advanced':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1314: undefined reference to `ZSTD_createDDict_advanced'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_sizeof_DCtx':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:82: undefined reference to `ZSTD_sizeof_DDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressBegin_usingDDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1222: undefined reference to `ZSTD_copyDDictParameters'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1213: undefined reference to `ZSTD_DDict_dictContent'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1214: undefined reference to `ZSTD_DDict_dictSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_clearDict':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:157: undefined reference to `ZSTD_freeDDict'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_decompress.c.o): in function `ZSTD_decompressStream':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1666: undefined reference to `ZSTD_DDict_dictContent'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/decompress/zstd_decompress.c:1667: undefined reference to `ZSTD_DDict_dictSize'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(zstd_opt.c.o): in function `ZSTD_rescaleFreqs':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/zstd_opt.c:176: undefined reference to `HIST_count_simple'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(fse_compress.c.o): in function `FSE_compress_wksp':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/fse_compress.c:656: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/fse_compress.c:656: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(huf_compress.c.o): in function `HUF_compressWeights':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:81: undefined reference to `HIST_count_simple'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(huf_compress.c.o): in function `HUF_compress_internal':
/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: /root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: undefined reference to `HIST_count_wksp'
/opt/rh/devtoolset-9/root/usr/bin/ld: contrib/zstd-cmake/libzstd.a(huf_compress.c.o):/root/clickhouse-rpm/rpmbuild/SOURCES/ClickHouse-19.14.13.4-lts/build/../contrib/zstd/lib/compress/huf_compress.c:661: more undefined references to `HIST_count_wksp' follow

**Comment by filimonov** [comment]
Mit looks like you did not update submodules, or keep cmake cache from old builds. Try building from the scratch

**Comment by i4late** [comment]
> it looks like you did not update submodules, or keep cmake cache from old builds. Try building from the scratch

i execute the commit  " git submodule update --init --recursive" at base dir. and all success .
